### ISSUE TITLE
Dynamically generated UI elements should be linked to activators

### ISSUE THREAD

**Issue by FrankTN** [RUGSoftEng/2017-Hestia-Client#10]
Classes for UI elements will be created which implement the UIwidget interface. This interface forces its implementations to store the deviceID and an activatorID. Using these ID's, the changed state of the UIwidget implementor can be sent to the correct activator on the server, using a POST method.

**Comment by StefanEvanghelides** [comment]
I think this is done, or at least, it was mentioned as done during the meeting.
Shall we close this issue?
