### ISSUE TITLE
Handle network timeout in case the app can't find the server

### ISSUE THREAD

**Issue by FrankTN** [RUGSoftEng/2017-Hestia-Client#13]
The app freezes and changes to a black screen when trying to log in. After approximately one minute it finally starts.

**Comment by Feikoritsema** [comment]
Thats not a login issue But network time-out, if the app cant find the server. Or did you get another error?

**Comment by FrankTN** [comment]
No that might be it, I was unable to debug it so I didn't see the stacktrace.

**Comment by Feikoritsema** [comment]
Stackoverflow link sent by Mark to fix, not fixed atm.

**Comment by FrankTN** [comment]
AsyncTask was called in an incorrect manner, blocking the main thread.
