### ISSUE TITLE
Future decisions

### ISSUE THREAD

**Issue by StefanEvanghelides** [RUGSoftEng/2017-Hestia-Client#130]
Here's a list of TODO's found in the code. This issue is meant a way of collecting all of them and deciding what to do next based on them. I also included a basic stack trace of their location:

- ExpandableDeviceList - getChildView (line ~43): move the slide diaog into the device class
- HomeActivity - onResume (line ~71): update the device list fragment
- AddDeviceInfo - pressConfirm - onPostExecute (line ~117) : find a way to update the GUI from here
- ChangeNameDialog - pressConfirm - onPostExecute(line ~62): update the GUI
- IpDialog - pressConfirm (line ~39): refresh layout
- IpDialog - pressConfirm (line ~43): give correct response from server after changing ip
- SlideDialog - createSeekBar - onStopTrackingTouch - onPostExecute (line ~110):  Update GUI
- DeviceBar - checked - onPostExecute (line ~175): Update GUI
- DeviceBar - deleteRequest - onPostExecute (line ~205): Update GUI

**Comment by FrankTN** [comment]
Very nice!

**Comment by StefanEvanghelides** [comment]
This issue could be closed as well. What has been done:
- automatic refresh after certain actions. 8/9 points solved.
- Slide dialog inside device class was not done, but we can create a separate issue for it, if needed.
