### ISSUE TITLE
Setting new IP address and Port number

### ISSUE THREAD

**Issue by StefanEvanghelides** [RUGSoftEng/2017-Hestia-Client#14]
We should be able to set up a new IP address and a new port number before we attempt to log in.
Maybe using a button?

**Comment by Feikoritsema** [comment]
I do not agree that this should be before login. I think after login we should first check:
- is there IP set ? Then load list
- else: open dialog to set IP , load list

**Comment by LarsHoldijk** [comment]
what Stefan proposed is necessary for later versions. By then login won't just be local anymore and you need the ip of the server before login in otherwise there is no way of login in.

**Comment by Feikoritsema** [comment]
Not necessarily, because the first login is with a standard name and pass provided by us anyways.
So it could be that the ip is after the login (which I personally prefer, but we can talk about this saturday)

**Comment by Feikoritsema** [comment]
Think this one can be closed for now. Ip is set when logging in, and can be changed.
