### ISSUE TITLE
IP address and port number remembered throughout the use of the App

### ISSUE THREAD

**Issue by StefanEvanghelides** [RUGSoftEng/2017-Hestia-Client#15]
This is not the most important, but it would be useful:

Ideally, when the IP address and port number are introduced for the first time, they would be remembered as defaults, so that if you are not sure what ip/port you introduced, you can see it there.

**Comment by Feikoritsema** [comment]
Yes I agree, already added the IP and Port in the ClientInteractionController.
Though I think we agreed on a standard port ?

**Comment by StefanEvanghelides** [comment]
We'll have to discuss with the Server team the fact that the Server should be able to try out multiple ports until it finds an open one, kind of the same thing that we did for AOOP course.
This is needed so that the app doesn't become useless if the server cannot actually start.

But for know, we shall focus on the way of preserving the ip and port number.

**Comment by FrankTN** [comment]
Anything which has to do with persistence can wait until the next sprint, we don't need to work on this now.

**Comment by FrankTN** [comment]
Anything which has to do with persistence can wait until the next sprint, we don't need to work on this now.

**Comment by StefanEvanghelides** [comment]
alright

**Comment by StefanEvanghelides** [comment]
This issue is fixed. Can safely be closed.
As for the persistence, we can open a new issue.
