### ISSUE TITLE
Once logged it, it doesn't retrieve the list of devices.

### ISSUE THREAD

**Issue by StefanEvanghelides** [RUGSoftEng/2017-Hestia-Client#16]
Debugging the app, I noticed that the problem is in DeviceListFragment, line 71, the one which has the command: 
`ArrayList<Device> devices = c.getDevices();`

Using the logger, the "devices" variable is null, which explains why nothing is printed.
Will check out this method. Maybe there is a problem with the deserialization.

**Comment by StefanEvanghelides** [comment]
Found the problem. It's in the ActivatorDeserializer. As I expected, the Server team changed organization of the JSON file, thus the deserialization is not done properly. It will be an easy fix. Should talk to them to see if we are going to change it in the future.

**Comment by StefanEvanghelides** [comment]
Will use these links as reference:
http://rowsandcolumns.blogspot.nl/2013/02/url-encode-http-get-solr-request-and.html
https://guides.codepath.com/android/Leveraging-the-Gson-Library

**Comment by FrankTN** [comment]
Once the deviceListActivity is initialized, an AsyncTask to obtain the devices starts running in the background. The DeviceListFragment listens to the results of this task, and the GUI is updated as soon as the AsyncTask returns. 

The issue with the formatting has also been resolved.
