### ISSUE TITLE
HestiaSwitch should be set in a less cumbersome manner

### ISSUE THREAD

**Issue by markhelmus** [RUGSoftEng/2017-Hestia-Client#22]
Currently, the setOnClickListener is set to null, then its layout state is set to a boolean value kept track of in the HestiaSwitch. After this procedure, the setOnClickListener is given its needed functionality (Posting the state to the server).

**Comment by StefanEvanghelides** [comment]
Was this fixed? I don't see this issue in the code.

**Comment by StefanEvanghelides** [comment]
Fixed this issue when working on the asynctasks. Now it is in the 'development' branch.
