### ISSUE TITLE
Change TravisCI in README to reflect master branch build status

### ISSUE THREAD

**Issue by FrankTN** [RUGSoftEng/2017-Hestia-Client#54]
Currently, TravisCI is tracking the development branch

**Comment by StefanEvanghelides** [comment]
After giving it some though, it is not actually bad that it reflects the state of development branch. We never want to have a broken feature there, so it should be fine.

**Comment by FrankTN** [comment]
Alright, I agree. The default target is master though, and I think when we are releasing we should set the README to reflect the release build status, so that it is not tracking the dev-branch on the master. 

On another note, we should also set the development branch as the target for the test coverage badge.

**Comment by StefanEvanghelides** [comment]
I believe we can close this issue now.
