### ISSUE TITLE
1-letter variables in UI classes

### ISSUE THREAD

**Issue by StefanEvanghelides** [RUGSoftEng/2017-Hestia-Client#60]
There still some 1-letter variables in the UI package.  Those should be removed by the end of this sprint.

**Comment by Feikoritsema** [comment]
Fixed as far as I know now.

**Comment by StefanEvanghelides** [comment]
Not really, there are a lot of default variables and methods that use 1-letter variables, such as View v, Activity a, etc

**Comment by Feikoritsema** [comment]
Should have mentioned that this is in the Uirefactoring branch
