### ISSUE TITLE
Low test coverage

### ISSUE THREAD

**Issue by FrankTN** [RUGSoftEng/2017-Hestia-Client#73]
To view the most recent test coverage report, visit: https://codecov.io/gh/RUGSoftEng/2017-Hestia-Client and switch to the branch you are interested in. Here you will find a detailed report of our current coverage. 

I think we should strive for at least 85% coverage in the backend. The GUI can have a lower percentage, as it is hard to write tests for everything there, but it is still important that it is also covered.

The **Requests** package has only 36% coverage, even though it contains very important functionality. This should be fixed.

The **GUI** is currently at only  34% coverage and desperately needs an update.

**Comment by FrankTN** [comment]
We are up to 55% now

**Comment by StefanEvanghelides** [comment]
I believe that this is not an issue that needs to open anymore. Close it when you see fit.

**Comment by StefanEvanghelides** [comment]
Currently, we are down to 30%. We shall greatly improve this during the last sprint

**Comment by StefanEvanghelides** [comment]
I believe we can close this issue, as it is not relevant anymore.
